name: Node.js CI

on:
  push:
    branches: ["main"]
    paths:    ["eponyms/**"]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - name: Update eponyms
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: node ./ulitza.js update

    - uses: EndBug/add-and-commit@v9
      with:
        add: '["eponyms.js", "eponyms.min.js"]'
        author_name: Mihai
        message: "update eponyms from CI"
